### ISSUE TITLE
Crashes with

### ISSUE THREAD

**Issue by MRNFN80** [toc-irc/jservices#3]
ircd@vps271076:~/jservices$ sudo node services.js
/home/ircd/jservices/services.js:78
                  if(this.uid.substr(0,3)==this.target.SID) {
                              ^

TypeError: Cannot read property 'substr' of undefined
    at Socket.<anonymous> (/home/ircd/jservices/services.js:78:31)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by realrasengan** [comment]
https://github.com/toc-irc/jservices/commit/35cd4e936494f3b183db7187874180be05eff33e
